package com.puttysoftware.riskyrescue.assets;

public enum ObjectImage {
    ARMOR, ARROW_EAST, ARROW_NORTH, ARROW_NORTHEAST, ARROW_NORTHWEST, ARROW_SOUTH, ARROW_SOUTHEAST, ARROW_SOUTHWEST, ARROW_WEST, BUTTON, CLOSED_DOOR, GROUND, HAZARD, HEALER, ITEMS, MONSTER, OFF_WALL, OPEN_DOOR, REGENERATOR, SPELLS, WALL, WEAPONS, DARKNESS, DOWN, EMPTY, NOTE, SEALING_WALL, UP
}
